dist: trusty
sudo: required

addons:
  sonarcloud:
    organization: "alexfoglia1-github"
    token:
      secure: "SwrnrNU8NYVOeTmnb1C9aNAehnsIs9nOTV2YwoKvgDsDdUUVBSpdCbwNbBEec2S6EJ6EEZ/Xilu6TGdGDULBaP9qKmZ45fSo6rAMCuH8phRE6hEOfnuRxBRSgoqbjT0Yjn9OdaosxJiMdQ1a7Zvd4/P9jZXa60DAWj/aDTBluEF913uE3zFHqqyL5ElcyVRWQgf9JH1IglTHtYt9pMx5Y4eY0uSragqZ/qqPXbJhB3yPhLHFIzjbfMqB4oWPJkEOcG1ez9/V3rC42mQzI06gjv7f75m7FfHqdX8gKyj88CriRwl5KVGfwtsK1Dr1ZhMNnKo8lR/5e3ygehQ3uykg2SYvQyPV8h+BmtOXQgES7PwQT3BGORSnaYp+LEODv+BDUNKzTG88xBsMjRBT5Aqv7LkwIDPwU/APkIgKEox2/jc6OTWz+0R6Y9rJO3Xvpn/i+Opne1pmllKOcTDX8Tqasd77mZix3eKh9z+SWaqax/MiAeFUiq6oA5NixGx2IWChGyhbKEhlJWINFUl0l7ZngJsDqclgAJ2YkiQOoM7J4j3JBnBt3ewOQkErHslbvpvH1C7NeRu8dqwUWEtsGZm5DF6++EaeRMgLz4oWk2Gz1f1XmpYYX3s7yZAnx0J8b3mL6L25Nqg8u6RwKxpRdKnOCSc6zja7yyXyiOwpAWRExys="

script:
  - build-wrapper-linux-x86-64 --out-dir bw-output make clean all
  - sonar-scanner
cache:
  directories:
    - '$HOME/.sonar/cache'
